esphome:
  project:
    version: dev # replaced at build time with the release tag by publish-firmware

packages:
  core: !include omgiavc.yaml

dashboard_import:
  package_import_url: github://jhbruhn/omgiavc-firmware/firmware/omgiavc.yaml@main

ota:
  - platform: http_request

http_request:

update:
  - platform: http_request
    name: None
    id: http_firmware_update
    update_interval: never
    source: https://jhbruhn.github.io/omgiavc-firmware/firmware/omgiavc.manifest.json

button:
  - platform: template
    name: "Check for Update"
    entity_category: diagnostic
    on_press:
      - update.check:
          id: http_firmware_update
